### PR TITLE
Close and dispose Sequel connections

### PR DESCRIPTION
**Pull request by jochenehret**
* we experience high memory usage of the admin-ui; heap dumps show that the "lib/sequel/adapters/postgres.rb" class has the highest memory usage and object count
-> properly close Sequel connections as recommended e.g. by http://stackoverflow.com/questions/14798856/ruby-sequel-memory-leak

### CODE REVIEW

**Comment by jochenehret** [comment]
Just joined org SAP-cloudfoundry which has a CLA -> closing and reopening PR.

**Comment by jochenehret** [comment]
Was not "public" member in sap-cloudfoundry org -> closing and reopening again.

**Comment by rboykin** [comment]
Since I am using Sequel.connect with a block, the disconnect and Sequel.synchronize{::Sequel::DATABASES.delete(db)} area already done.  See https://github.com/jeremyevans/sequel/blob/master/lib/sequel/database/connecting.rb#L66-77

**Comment by jochenehret** [comment]
Ok, we weren't sure if the database connections were properly closed.

**Pull request closed without merging**
